config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :images
  resources :galleries, except: [:index, :destroy] do
    resources :images, only: [:show]
    member do
      # get  'shares/new'    => 'galleries#new_share',    as: :new_share
      get  'shares/create' => 'galleries#create_share', as: :create_share
    end
  end

  root              'session#stage'
  get  '/login'  => 'session#new'
  post '/login'  => 'session#create'
  get  '/logout' => 'session#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord

  belongs_to :user, counter_cache: true
  has_many :imagings
  has_many :images, through: :imagings

  validates :title, presence: true, allow_blank: false
  validates_uniqueness_of :title, scope: :user

  default_scope { order(created_at: :desc) }

end

app/models/image.rb
class Image < ApplicationRecord

  attr_reader :file_remote_url

  has_many :imagings
  has_many :galleries, through: :imagings
  belongs_to :user

  validates :file, presence: true
  has_attached_file :file, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :file, content_type: /\Aimage\/.*\z/

  default_scope { order(created_at: :desc) }

  def file_remote_url=(url)
    self.file = URI.parse(url)
    @file_remote_url = url
  end

end

app/models/imaging.rb
class Imaging < ApplicationRecord

  belongs_to :gallery
  belongs_to :image

  validates :gallery, presence: true
  validates :image, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord

  has_many :galleries
  has_many :images

  has_secure_password

  validates :username, :email, presence:    true,
                               allow_blank: false,
                               uniqueness:  true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action ->{
    @title = 'imgrrr'
  }

  private

  helper_method def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    if !current_user
      flash[:warning] = "Go on, login or sign up. You know you want to!"
      redirect_to login_path
    end
  end

end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :require_user, only: [:new, :create, :create_share, :edit, :update, :destroy]

  def show
    # @gallery_mailer = GalleryMailer.new()
    @gallery = Gallery.includes(:images).find(params[:id])
  end

  def new
    @gallery = Gallery.new
  end

  def create_share
    GalleryMailer.share(params[:gallery_mailer][:recipient_name], params[:gallery_mailer][:recipient_email], params[:gallery_mailer][:gallery_url], current_user).deliver
    respond_to do |format|
      format.html # send html back
      format.js # send javascript
    end
    # flash[:success] = 'Yay! You\'ve successfully given up some private information! Expect a creepy email from us confirming your admission into the mainframe.'
  end

  def create
    @gallery = current_user.galleries.new(gallery_params)
    if @gallery.save
      redirect_to @gallery
    else
      render :new
    end
  end

  def edit; end

  def update
    case params[:commit]
    when 'Update Gallery'
      gallery.update!(gallery_params)
    when 'Delete Gallery'
      destroy
    end
    redirect_to current_user
  end

  def destroy
    gallery.images.each do |image|
      member_galleries = Image.find(image.id).galleries
      if member_galleries.count > 1
        gallery.images.delete(image.id)
      else
        Imaging.find_by(image_id: image.id).delete
        Image.find(image.id).delete
      end
    end
    gallery.destroy!
  end

  private

  helper_method def galleries
    @galleries ||= User.find(session[:user_id]).galleries.all
  end

  helper_method def gallery
    # @gallery ||= galleries.find_by(user_id: params[:id])
    @gallery ||= User.find(session[:user_id]).galleries.includes(:images).find(params[:id])
  end

  def gallery_params
    params.require(:gallery).permit(:title, :description, :image)
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    @images = Image.all
  end

  def show
    if params[:gallery_id]
      gallery_id = params[:gallery_id].to_i
      image_id = params[:id].to_i
      if Gallery.pluck(:id).include? gallery_id
        gallery = Gallery.find(gallery_id)
        if gallery.images.pluck(:id).include? image_id
          @image = images.find(image_id)
          render template: 'images/context'
        end
      else
        redirect_to '/'         #TODO: refactor: render error
      end
    end
  end

  def new
    @image = Image.new
  end

  def create
    @image = current_user.images.new(image_params)
    if @image.save
      galleries = params[:image][:gallery_ids].reject { |g| g.to_s.empty? }
      galleries.each do |g|
        target_gallery = Gallery.find(g)
        if target_gallery.user == current_user
          target_gallery.images << @image
          target_gallery.save
        else
          redirect_to '/logout'
        end
      end
      redirect_to @image
    else
      render :new
    end
  end

  private

  helper_method def images
    @images ||= Image.all
  end

  helper_method def image
    @image ||= images.find(params[:id])
  end

  def image_params
    params.require(:image).permit(:title, :caption, :file, :gallery_ids)
  end

end

app/controllers/imagings_controller.rb
class ImagingsController < ApplicationController
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def stage
    redirect_to current_user if current_user
  end

  def new; end

  def create
    @user = User.find_by(username: params[:session][:username])

    if @user&.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:success] = "You're logged in, #{@user.username}"
      redirect_to @user
    else
      flash[:danger] = 'Invalid username or password. Try again.'
      redirect_to :login
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index; end
  def show; end
  def update; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.signup(@user).deliver
      session[:user_id] = @user.id
      flash[:success] = 'Yay! You\'ve successfully given up some private information! Expect a creepy email from us confirming your admission into the mainframe.'
      redirect_to @user
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username,
                                 :email,
                                 :avatar,
                                 :password)
  end

  def require_self
    if user != current_user
      flash[:danger] = "Nope."
      redirect_to :root
    end
  end

  helper_method def users
    @users ||= User.all
  end

  helper_method def user
    @user ||= users.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/imagings_helper.rb
module ImagingsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_core.html.erb
<section id="site-core" class="column">
    <div class="row center-block">
      <main id="content" class="col-lg-6 col-lg-offset-2">

        <%= yield %>

      </main>
    </div>
</section>

app/views/application/_footer.html.erb
<footer id="site-footer">
    Copyright &copy; 2017
</footer>

app/views/application/_header.html.erb
<header id="site-header">
    <h1>
        <%= link_to root_path do

            @title
            
        end %>
    </h1>
</header>

app/views/application/_logout_button.html.erb
<a class="btn btn-warning" href="/logout" role="button">Logout</a>

app/views/application/_nav.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <strong><%= link_to @title, root_path %></strong>
            <em>
              <%= "You are #{'not' if !current_user} logged in#{' as ' + current_user.username if current_user}." %>
              <%= render 'logout_button' if current_user %>
            </em>
        </div>
    </div>
</nav>

app/views/galleries/_form.html.erb
<%= simple_form_for gallery do |f| %>

  <%= f.input  :title %>
  <%= f.input  :description, as: :text %>
  <%= f.button :submit, class: 'btn btn-primary' %>

<% end %>

app/views/galleries/_share_modal.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="share_modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Share Gallery</h4>
      </div>



        <%= simple_form_for :gallery_mailer, url: create_share_gallery_path(gallery), method: :get, dismiss: "share_modal", remote: true do |f| %>
          <div class="modal-body">
            <%= f.input :recipient_name %>
            <%= f.input :recipient_email %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <%= f.button :submit, "Share!", class: "btn btn-primary", data: {dismiss: 'modal'} %>
            <%#= link_to create_share_gallery_path, remote: true, id: 'new_share_link' do %>
              <%#= f.button :submit, "Share!", class: "btn btn-primary" %>
            <%# end %>
          </div>
        <% end %>




    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/galleries/edit.html.erb
<h1><%= gallery.title %></h1>
<% if !gallery.images %>
    This gallery is empty. Fill it with your best slow loris photos!
<% else %>
  <% gallery.images.each do |i| %>
    <div class="col-lg-3 text-center">
      <%= link_to i, class: 'thumbnail' do %>
        <%= image_tag i.file.url(:thumb), class: 'img-responsive' %>
        <%= simple_format i.title, class: 'caption' %>
      <% end %>
    </div>
  <% end %>
  <%= simple_form_for gallery do |g| %>
    <%= g.input  :title %>
    <%= g.input  :description, as: :text %>
    <%= g.button :submit, 'Update Gallery', class: 'btn btn-primary' %>
    <%= g.button :submit, 'Delete Gallery', class: 'btn btn-danger' %>
  <% end %>
<% end %>

app/views/galleries/new.html.erb
<h1>Create a gallery for all your photos of PUPPIES!</h1>

<%= render "form" %>

app/views/galleries/show.html.erb
<h1><%= gallery.title %></h1>
<% if !gallery.images %>
    This gallery is empty. Fill it with your best slow loris photos!
<% else %>
  <% gallery.images.each do |i| %>
    <div class="col-lg-3 text-center">
      <%= link_to i, class: 'thumbnail' do %>
        <%= simple_format i.title, class: 'caption' %>
        <%= image_tag i.file.url(:thumb), class: 'img-responsive' %>
        <%= simple_format i.caption, class: 'caption' %>
      <% end %>
    </div>
  <% end %>
  <%= link_to '/images/new' do %>
    <button class="btn btn-primary">Add</button>
  <% end %>
  <%= link_to "#share_modal", title: 'Share Gallery', class: 'btn btn-info btn-sm', data: {toggle: 'modal'} do%>
     <i class="glyphicon glyphicon-share"></i>&nbsp;Share Gallery
  <% end %>

  <%= render 'share_modal' %>

<% end %>

app/views/images/context.html.erb
  <div class="col-lg-3">
    <%= link_to @image.file.url, class: "btn btn-default" do %>
      <%= simple_format @image.title %>
      <%= image_tag @image.file.url %>
    <% end %>
  </div>

app/views/images/index.html.erb
<% images.each do |i| %>
  <div class="col-md-3 col-sm-6">
    <%= link_to i, class: "btn btn-default" do %>
      <%= simple_format i.title %>
    <% end %>
  </div>
<% end %>

app/views/images/new.html.erb
<%= simple_form_for image do |f| %>
  <%= f.input  :title %>
  <%= f.input  :caption, as: :text %>
  <%= f.input  :file, as: :file %>
  <%= f.association :galleries, collection: current_user.galleries %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/images/show.html.erb
<div class="col-lg-12 text-center">
  <%= link_to image.file.url, class: "thumbnail" do %>
    <%= simple_format image.title %>
    <%= image_tag image.file.url(:medium) %>
  <% end %>
  <% image.galleries.each do |g| %>
    <%= link_to g.title, g, class: 'bg-info' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= @title %></title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <%= render partial: 'nav'    %>
        <%= render partial: 'header' if request.env['PATH_INFO'] == root_path %>
        <%= render partial: 'core'   %>
        <%= render partial: 'footer' %>
        <%= render partial: 'share_modal' %>
    </body>
</html>

app/views/session/_form.html.erb
<%= simple_form_for :session do |f| %>
  <%= f.input :username %>
  <%= f.input :password %>
  <%= f.button :submit, 'Login', class: 'btn btn-primary' %>
<% end %>

app/views/session/new.html.erb
<h1>Log In!</h1>

<%= render 'form' %>

app/views/session/stage.html.erb
<div id="stage" class="container">
  <div class="row">
    <div class="col-lg-12 text-center">

      <h1>Share your cutest things with us!!</h1>


      <div class="alert">
        <h2>
          Post photos. Make galleries. Share them.
        </h2>
      </div>

      <a class="btn btn-default" href="/login" role="button">Sign in!</a>
      <a class="btn btn-primary" href="/users/new" role="button">Sign up!</a>

    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= simple_form_for @user do |form| %>

  <%= form.input  :username %>
  <%= form.input  :email    %>
  <%= form.input  :password %>
  <%= form.input  :avatar   %>
  <%= form.button :submit   %>

<% end %>

app/views/users/index.html.erb
<% users.each do |u| %>
  <div class="col-lg-3">
    <%= link_to u, class: "btn btn-default" do %>
      <%= image_tag u.avatar, class: "img-responsive" %>
      <%= simple_format u.username, class: 'caption' %>
    <% end %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Register an account</h1>

<%= render "form" %>

app/views/users/show.html.erb
<div class="container">

    <div class="row">
        <div class="col-lg-3 text-center">
            <%= link_to user, class: 'btn btn-default' do %>
              <%= image_tag user.avatar, class: 'img-responsive' %>
            <% end %>
            <h3><strong>&ldquo;</strong><%= user.username %><strong>&rdquo;</strong></h3>
            <%= simple_format flash[:success], class: 'bg-success' if flash[:success] %>
        </div>
        <div class="col-lg-9">

            <% user.galleries.each do |g| %>
              <div class="col-lg-3 text-center">
                  <%= link_to g, {class: 'thumbnail', target: '_blank'} do %>
                    <%= simple_format g.title, class: 'bg-primary' %>
                    <%  most_recent_image = g.images.last %>
                    <%= image_tag most_recent_image.file.url(:thumb), class: 'img-responsive' %>
                    <%= simple_format g.description, class: 'caption' %>
                    <small><%= simple_format distance_of_time_in_words(most_recent_image.created_at, Time.now), class: 'text-muted' %></small>
                  <% end %>
              </div>
            <% end %>

        </div>
    </div>

</div>